# Generated by Django 5.0.1 on 2024-01-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist_user',
            name='email',
            field=models.EmailField(default='userone@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='playlist_user',
            name='password',
            field=models.CharField(default=1234, max_length=200),
        ),
        migrations.AlterField(
            model_name='playlist_user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
