# Generated by Django 5.0.1 on 2024-01-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_playlist_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist_user',
            name='email',
            field=models.EmailField(default='userone@gmail.com', max_length=254, unique=True),
        ),
    ]
