# Generated by Django 5.0.1 on 2024-01-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_add_default_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='playlist_user',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
